name: Deploy Apps Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write   # needed for Workload Identity if you choose that auth method
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          # Use one of these methods:
          # 1. Service account JSON stored as a secret:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          # 2. Or, use Workload Identity Federation:
          # workload_identity_provider: projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider
          # service_account: my-sa@my-project.iam.gserviceaccount.com

      - name: Deploy to Apps Script
        uses: google-github-actions/deploy-apps-script@v0
        with:
          script_id: ${{ secrets.CLASP_SCRIPT_ID }}
          # path to your Apps Script source, relative to repo root:
          project: src
