name: Deploy Apps Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Write OAuth JSON
        run: |
          # Accept either raw JSON or base64-encoded JSON in CLASP_OAUTH_JSON
          RAW_SECRET="${{ secrets.CLASP_OAUTH_JSON }}"
          # Trim leading spaces/newlines for detection
          FIRST_CHAR=$(printf '%s' "$RAW_SECRET" | tr -d '\r' | sed 's/^\s*//' | head -c 1)
          if [ "$FIRST_CHAR" = "{" ]; then
            printf '%s' "$RAW_SECRET" | tr -d '\r' > oauth.json
          else
            printf '%s' "$RAW_SECRET" | tr -d '\r' | base64 -d > oauth.json
          fi
          # Validate JSON to fail fast with a clear error
          jq -e . oauth.json > /dev/null

      - name: Login to clasp (headless)
        run: npx --yes @google/clasp login --no-localhost --creds ./oauth.json

      - name: Create .clasp.json
        run: |
          cat <<EOF > .clasp.json
          {
            "scriptId": "${{ secrets.CLASP_SCRIPT_ID }}",
            "rootDir": "src"
          }
          EOF

      - name: Push to Apps Script
        run: npx --yes @google/clasp push --force
