name: Deploy Apps Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Write OAuth JSON
        run: |
          echo "${{ secrets.CLASP_OAUTH_JSON }}" > oauth.json

      - name: Login to clasp (headless)
        run: npx --yes @google/clasp login --no-localhost --creds ./oauth.json

      - name: Create .clasp.json
        run: |
          cat <<EOF > .clasp.json
          {
            "scriptId": "${{ secrets.CLASP_SCRIPT_ID }}",
            "rootDir": "src"
          }
          EOF

      - name: Push to Apps Script
        run: npx --yes @google/clasp push --force
