name: Deploy Apps Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install clasp
        run: npm install -g @google/clasp

      - name: Configure GCP Credentials
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          echo "$GCP_CREDENTIALS" > gcp-key.json
          # Экспорт пути к ключу для Google библиотеки
          echo "GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/gcp-key.json" >> $GITHUB_ENV
          # Аутентификация сервисного аккаунта в gcloud (необязательно для clasp)
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud config set project calendar-availabilities-473113

      - name: Create .clasp.json
        run: |
          cat <<EOF > .clasp.json
          {
            "scriptId": "${{ secrets.CLASP_SCRIPT_ID }}",
            "rootDir": "src"
          }
          EOF

      - name: Push to Apps Script
        run: clasp push --force
