name: Deploy Apps Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install clasp
        run: npm install -g @google/clasp

      - name: Configure GCP Credentials
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          echo "$GCP_CREDENTIALS" > creds.json
          gcloud auth activate-service-account --key-file=creds.json
          gcloud config set project YOUR_GCP_PROJECT_ID

      - name: Login clasp with credentials
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          echo "$GCP_CREDENTIALS" > gcp-key.json
          clasp login --creds gcp-key.json

      - name: Push to Apps Script
        env:
          CLASP_SCRIPT_ID: ${{ secrets.CLASP_SCRIPT_ID }}
        run: |
          clasp push --force --script-id $CLASP_SCRIPT_ID
